[workspace]
members = [
    "plt",
    "plt-draw",
    "plt-cairo",
]

[workspace.package]
edition = "2021"
authors = ["Jonah Hoffman <jhh451@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/plt-rs/plt"
